#| filename: "deployment/deployment.yaml"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-deployment
  labels:
    app: titanic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
      - name: titanic
        image: linogaliana/application:latest
        ports:
        - containerPort: 8000
        env:
        - name: JETON_API
          valueFrom:
            secretKeyRef:
              name: api-jeton
              key: JETON_API
